title: My Personal Space
email: domain.username@gmail.com
description: "A Goan Sushegaad Life."
url: "https://diaryofravi.github.io"
baseurl: "/me"

permalink: /:categories/:year/:month/:day/:title/
markdown: kramdown
theme: minima




